apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-tripviewer
  namespace: web
  labels:
    app: tripviewer-tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryqzu2798.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: TRIPS_API_ENDPOINT
          value: 'http://api.trips'
        - name: USERPROFILE_API_ENDPOINT
          value: 'http://api.userprofile'
        - name: ASPNETCORE_ENVIRONMENT
          value: 'Development'
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata: 
  name: tripviewer
  namespace: web
spec:
  ports: 
  - port: 80
  selector: 
    app: tripviewer