apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-userjava
  namespace: api
  labels:
    app: userjava-userjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryqzu2798.azurecr.io/tripinsights/user-java:1.0
        volumeMounts:
          - name: openhack-secrets
            mountPath: "/secrets"
            readOnly: true
        ports:
           - containerPort: 80
      volumes:
        - name: openhack-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "openhack-secrets"
---
apiVersion: v1 
kind: Service 
metadata: 
  name: user-java 
  namespace: api
spec:
  ports: 
  - port: 80
  selector: 
    app: user-java