apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-userjava
  labels:
    app: userjava-userjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryqzu2798.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata: 
  name: user-java 
spec:
  ports: 
  - port: 80
  selector: 
    app: user-java