apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjava-userjava
  namespace: api
  labels:
    app: userjava-userjava
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryqzu2798.azurecr.io/tripinsights/user-java:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql
              key: SQL_PASSWORD
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sql
              key: SQL_DBNAME
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sql
              key: SQL_SERVER
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata: 
  name: user-java 
spec:
  ports: 
  - port: 80
  selector: 
    app: user-java