apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-trips
  namespace: api
  labels:
    app: trips-trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - name: trips
          image: registryqzu2798.azurecr.io/tripinsights/trips:1.0
          volumeMounts:
          - name: openhack-secrets
            mountPath: "/secrets"
            readOnly: true
          ports:
           - containerPort: 80
      volumes:
        - name: openhack-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "openhack-secrets"
---
apiVersion: v1 
kind: Service 
metadata: 
  name: trips 
  namespace: api
spec:
  ports: 
  - port: 80
  selector: 
    app: trips