apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-poi
  namespace: api
  labels:
    app: poi-poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryqzu2798.azurecr.io/tripinsights/poi:1.0
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql
                key: SQL_PASSWORD
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sql
                key: SQL_DBNAME
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sql
                key: SQL_SERVER
          - name: WEB_SERVER_BASE_URI
            value: 'http://api.poi'
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata: 
  name: poi 
  namespace: api
spec:
  ports: 
  - port: 80
  selector: 
    app: poi