apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-poi
  namespace: api
  labels:
    app: poi-poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryqzu2798.azurecr.io/tripinsights/poi:1.0
        volumeMounts:
          - name: openhack-secrets
            mountPath: "/secrets"
            readOnly: true
        env:
          - name: WEB_SERVER_BASE_URI
            value: 'http://api.poi'
        ports:
           - containerPort: 80
      volumes:
        - name: openhack-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "openhack-secrets"
---
apiVersion: v1 
kind: Service 
metadata: 
  name: poi 
  namespace: api
spec:
  ports: 
  - port: 80
  selector: 
    app: poi