apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-userprofile
  namespace: api
  labels:
    app: userprofile-userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryqzu2798.azurecr.io/tripinsights/userprofile:1.0
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sql
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql
              key: SQL_PASSWORD
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sql
              key: SQL_DBNAME
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sql
              key: SQL_SERVER
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata: 
  name: userprofile 
spec:
  ports: 
  - port: 80
  selector: 
    app: userprofile