apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-userprofile
  namespace: api
  labels:
    app: userprofile-userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryqzu2798.azurecr.io/tripinsights/userprofile:1.0
        volumeMounts:
          - name: openhack-secrets
            mountPath: "/secrets"
            readOnly: true
        ports:
           - containerPort: 80
      volumes:
        - name: openhack-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "openhack-secrets"
---
apiVersion: v1 
kind: Service 
metadata: 
  name: userprofile 
  namespace: api
spec:
  ports: 
  - port: 80
  selector: 
    app: userprofile