apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-userprofile
  labels:
    app: userprofile-userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile
        image: registryqzu2798.azurecr.io/tripinsights/userprofile:1.0
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata: 
  name: userprofile 
spec:
  ports: 
  - port: 80
  selector: 
    app: userprofile